### ISSUE TITLE
IndexError: list index out of range on analysis list

### ISSUE THREAD

**Issue by emi-netlist** [medwatt/gmid#2]
```
/lookup_table_generator.py", line 114, in __save_ngspice_parameters
    column_names = analysis[0].dtype.names
IndexError: list index out of range
```

Can somebody please tell me what am I doing wrong?

**Comment by medwatt** [comment]
@emi-netlist, since you didn't say what you were doing, I am going to assume that you used a model for which ngspice did not generate one of the parameters it is looking for in the table.

1. First try generating a lookup table for a freepdk 45nm transistor. The model can be found [here](https://github.com/baichen318/FreePDK45/tree/main/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom).

2. If the above works, which it should, then it means that the model you're using did not generate one of the parameters it is looking for in the table. What you can do is run the spice netlist that the the code generates at the beginning, and check which of the parameters in the table are produced by the model you're using.

**Comment by HarikrishnaKayitha** [comment]
Though I have tried generating a LUT for a freepdk45nm transistor. I am facing the same error. 
What might be the reason for that?
How can it be resolved?

On the other end, when I tried doing for a transistor from the 65nm model. I am getting an error at line no. 18 in main.py

def load_lookup_table(path: str):
                                           ^
Syntax Error: Invalid Syntax


Can someone tell how to deal with these 2 errors?

**Comment by medwatt** [comment]
@HarikrishnaKayitha,  you can't expect me to know the cause of the error if you don't provide any information. The Syntax Error you mentioned makes no sense unless you have modified the source code or maybe you're using some very incompatible version of python.

**Comment by HarikrishnaKayitha** [comment]
Hi @medwatt, I am using the python 3.11

![Screenshot 2024-03-22 145248](https://github.com/medwatt/gmid/assets/106346019/747b169e-2e63-4d70-8ffc-d2f94a2b289b)

I haven't modified source code.

**Comment by medwatt** [comment]
@HarikrishnaKayitha, I don't use windows. Can you confirm that you have `ngspice` installed and that you can call it from the command line?

**Comment by HarikrishnaKayitha** [comment]
Hi @medwatt 

ngspice is installed. I have tried using it from Pycharm. Since it is a limited version, I am unable to connect the python interpreter with ngspice. I have installed WSL and tried accessing it. 
I would like to hear whether there are any other possible ways to link ngspice with python (for example by using any other python IDE doing this. or any other way)
Thank you for your responses
